apiVersion: v1
kind: Service
metadata:
  name: es-discovery-svc
  labels:
    app: es-discovery-svc
spec:
  # the set of Pods targeted by this Service are determined by the Label Selector
  selector:
    app: elasticsearch
  # exposing elasticsearch transport port (only)
  # this service will be used by es-nodes for discovery;
  # communication between es-nodes happens through the transport port (9300)
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  # specifying this is a headless service by providing ClusterIp "None"
  clusterIP: None
